### ISSUE TITLE
Droplet anchor IP is not being properly set

### ISSUE THREAD

**Issue by pirelenito** [macaco-maluco/macaco-maluco-infra#1]
The floating IP is not being properly setup in the CoreOS machine. Maybe caused by the use of `user_data`?

I've found [an article](https://www.digitalocean.com/community/tutorials/how-to-enable-floating-ips-on-an-older-droplet) on updating older Droplets to support floating IPS, which shouldn't be my scenario, but it indeed fix the problem.

## Fix

SSH into the machine, then.

First check what is the machine's **anchor IP**:

```bash
curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/anchor_ipv4/address
```

Then use the provided IP to update a configuration (remember to change it before executing):

```bash
sudo ip addr add 10.13.0.6/16 dev eth0
```

This is a temporary fix, and the machine is broken again on restart. Needs more investigation.

What I don't understand is that this is a fresh Droplet being created. Why is this not being correctly set? Maybe a DigitalOcean issue?

**Comment by fnmunhoz** [comment]
I couldn't figure out the problem. 

We may try a pair tomorrow. We can test with other SO droplet like ubuntu to isolate the problem.

It could be a Terraform issue as well.

**Comment by pirelenito** [comment]
This might be related: https://github.com/kontena/kontena/issues/531

**Comment by pirelenito** [comment]
Here is the probable fix: https://github.com/kontena/kontena/pull/532/files

**Comment by fnmunhoz** [comment]
It basically automates what you made manually, right?

**Comment by pirelenito** [comment]
Exactly
